# render.yaml
services:
  - type: web
    name: c9-frontend
    rootDir: frontend
    buildCommand: npm run build
    startCommand: npm run preview -- --port $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://c9-marketing.onrender.com/api
    buildFilter:
      paths:
        - frontend/**/*
    staticPublishPath: dist
