services:
  - type: static
    name: c9-frontend
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://c9-marketing.onrender.com/api
